import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { generateTables, injectGenerated, parseFrontmatter } from "./generate-tables.js";
const roots: string[] = []; const tick=String.fromCharCode(96);
afterEach(async () => Promise.all(roots.splice(0).map(root => rm(root,{recursive:true,force:true}))));
async function fixture(){const root=await mkdtemp(join(tmpdir(),"generate-tables-"));roots.push(root);for(const p of ["src/skills/alpha","src/skills/skill-creator","src/agents","src/recipes/subrecipes","src/app/eval-hub/evals/skills","src/app/eval-hub/evals/agents","src/app/eval-hub/evals/recipes","src/harness","docs/internal"])await mkdir(join(root,p),{recursive:true});await writeFile(join(root,"src/skills/alpha/SKILL.md"),"---\nname: alpha\ndescription: >\n  Alpha does the first thing. More detail.\n---\n");await writeFile(join(root,"src/skills/skill-creator/SKILL.md"),"---\ndescription: Hidden.\n---\n");await writeFile(join(root,"src/agents/builder.md"),"---\nname: builder\ndescription: Build safely. Then stop.\nmodel: claude-sonnet-4-5\n---\n");await writeFile(join(root,"src/recipes/flow.yaml"),"title: Flow\n");await writeFile(join(root,"src/recipes/subrecipes/ignored.yaml"),"title: ignored\n");await writeFile(join(root,"src/harness/external-skills.lock.json"),JSON.stringify({skills:[{name:"zeta",active:true,source:{repository:"org/repo"}},{name:"a_b",active:true,source:{repository:"org/under"}},{name:"a-b",active:true,source:{repository:"org/dash"}},{name:"éclair",active:true,source:{repository:"org/unicode"}},{name:"off",active:false,source:{repository:"x/y"}}]}));await writeFile(join(root,"src/app/eval-hub/evals/skills/alpha.json"),"[]");await writeFile(join(root,"src/app/eval-hub/evals/skills/zeta.json"),"[]");await writeFile(join(root,"src/app/eval-hub/evals/agents/builder.json"),JSON.stringify([{skills:["alpha"],agents:["ignored"]}]));await writeFile(join(root,"src/app/eval-hub/evals/recipes/flow.json"),JSON.stringify([{skills:["alpha","zeta"],agents:["builder"]}]));const marker=(n:string)=>"before\n<!-- BEGIN GENERATED: "+n+" -->\nstale\n<!-- END GENERATED: "+n+" -->\nafter\n";await writeFile(join(root,"README.md"),marker("skills-table")+marker("agents-table"));await writeFile(join(root,"docs/internal/15-skill-evaluations.md"),marker("eval-skills")+marker("eval-agents")+marker("eval-recipes"));return root;}
describe("generate tables",()=>{it("uses code-point order and is idempotent",async()=>{const root=await fixture();expect((await generateTables(root)).changed).toBe(5);const text=await readFile(join(root,"README.md"),"utf8");for(const [a,b] of [["a-b","a_b"],["a_b","zeta"],["zeta","éclair"]])expect(text.indexOf(tick+a+tick)).toBeLessThan(text.indexOf(tick+b+tick));expect(text).toContain("| "+tick+"builder"+tick+" | Build safely. | sonnet-4-5 |");const second=await generateTables(root);expect(second.changed).toBe(0);expect(second.stdout).toContain("0/5 section(s) updated.")});it("preserves missing markers and warns",async()=>{const root=await fixture();await writeFile(join(root,"README.md"),"no markers\n");const result=await generateTables(root);expect(result.stdout).toContain("[WARN] No marker found");expect(await readFile(join(root,"README.md"),"utf8")).toBe("no markers\n")});it("characterizes frontmatter and injection",()=>{expect(parseFrontmatter("---\nname: x\ndescription: \"A sentence. More\"\n---\n")).toEqual({name:"x",description:"A sentence. More"});expect(injectGenerated("a<!-- BEGIN GENERATED: x -->old<!-- END GENERATED: x -->b","x","new\n")).toEqual({text:"a<!-- BEGIN GENERATED: x -->\nnew\n<!-- END GENERATED: x -->b",changed:true,found:true})})});
