#!/usr/bin/env node
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readEvalLayers } from "@harness/eval-hub/measurement/evalCoverage";
type FM=Record<string,string>; type External={name:string;active?:unknown;source:{repository:string}};;
function firstSentence(value:string):string { const text=value.trim().replace(/^[> ]+/,"").trim().replace(/\s+/g," "); const dot=text.indexOf("."); return dot>0&&dot<100?text.slice(0,dot+1):text.slice(0,90).trimEnd(); }
export function parseFrontmatter(text:string):FM { const m=/^---\n([\s\S]*?)\n---/.exec(text); if(!m?.[1])return{}; const out:FM={}; for(const line of m[1].split("\n")){const kv=/^(\w[\w-]*):\s*(.*)/.exec(line);if(kv?.[1]!==undefined&&kv[2]!==undefined)out[kv[1]]=kv[2].trim().replace(/^"|"$/g,"");} return out; }
async function skillDescription(dir:string):Promise<string>{let text:string;try{text=await readFile(join(dir,"SKILL.md"),"utf8");}catch{return"";}const folded=/description:\s*>\n((?:  .+\n?)+)/.exec(text);if(folded?.[1])return firstSentence(folded[1].split("\n").map(x=>x.trim()).filter(Boolean).join(" "));const one=/description:\s*(.+)/.exec(text);return one?.[1]?firstSentence(one[1].trim().replace(/^"|"$/g,"")):"";}
async function dirs(path:string):Promise<string[]>{return(await readdir(path,{withFileTypes:true})).filter(x=>x.isDirectory()&&x.name!=="skill-creator").map(x=>x.name).sort();}
async function files(path:string,ext:string):Promise<string[]>{return(await readdir(path,{withFileTypes:true})).filter(x=>x.isFile()&&extname(x.name)===ext).map(x=>x.name).sort();}
async function exists(path:string):Promise<boolean>{try{await readFile(path);return true;}catch{return false;}}
export function injectGenerated(text:string,section:string,content:string):{text:string;changed:boolean;found:boolean}{const begin="<!-- BEGIN GENERATED: "+section+" -->",end="<!-- END GENERATED: "+section+" -->";const start=text.indexOf(begin),finish=text.indexOf(end,start+begin.length);if(start<0||finish<0)return{text,changed:false,found:false};const replacement=begin+"\n"+content.trimEnd()+"\n"+end,next=text.slice(0,start)+replacement+text.slice(finish+end.length);return{text:next,changed:next!==text,found:true};}
export interface GenerateResult{changed:number;total:number;stdout:string}
export async function generateTables(root:string):Promise<GenerateResult>{
 const skills=await dirs(join(root,"src/skills")),agents=await files(join(root,"src/agents"),".md"),recipes=await files(join(root,"src/recipes"),".yaml");
 const lock=JSON.parse(await readFile(join(root,"src/harness/external-skills.lock.json"),"utf8")) as {skills:External[]};const external=lock.skills.filter(x=>Boolean(x.active)).sort((a,b)=>a.name<b.name?-1:a.name>b.name?1:0);
 const tick="\x60";const sr=["## Skills ("+(skills.length+external.length)+")","","| Skill | Purpose |","|-------|---------|"];for(const name of skills)sr.push("| "+tick+name+tick+" | "+await skillDescription(join(root,"src/skills",name))+" |");for(const x of external)sr.push("| "+tick+x.name+tick+" | External locked skill from "+tick+x.source.repository+tick+". |");
 const ar=["## Named agents ("+agents.length+")","","Named agent sources in "+tick+"src/agents/"+tick+" — invoke with Goose Summon natural language:",tick+"load agent <name>"+tick+" (in-session) or "+tick+"delegate task bd-xxx and into those task load agent <name>"+tick+" (isolated).","","| Agent | Role | Model |","|-------|------|-------|"];for(const file of agents){const name=file.slice(0,-3),fm=parseFrontmatter(await readFile(join(root,"src/agents",file),"utf8")),desc=firstSentence(fm.description??"").slice(0,80),model=(fm.model??"").replaceAll("claude-opus-4-5","opus-4-5").replaceAll("claude-sonnet-4-5","sonnet-4-5");ar.push("| "+tick+name+tick+" | "+desc+" | "+model+" |");}
 const es=["| Skill | Eval file |","| --- | --- |"] as string[];for(const name of [...skills,...external.map(x=>x.name)])if(await exists(join(root,"src/app/eval-hub/evals/skills",name+".json")))es.push("| "+tick+name+tick+" | "+tick+"evals/skills/"+name+".json"+tick+" |");
 const ea=["| Agent | Eval file | Supporting skills (Layer 1 baseline) |","| --- | --- | --- |"] as string[];for(const file of agents){const name=file.slice(0,-3);if(await exists(join(root,"src/app/eval-hub/evals/agents",name+".json"))){const l=await readEvalLayers(root,"agents",name);ea.push("| "+tick+name+tick+" | "+tick+"evals/agents/"+name+".json"+tick+" | "+l.skills.map(x=>tick+x+tick).join(", ")+" |");}}
 const er=["| Recipe | Eval file | In-session agents (Layer 2) | Skills (Layer 1) |","| --- | --- | --- | --- |"] as string[];for(const file of recipes){const name=file.slice(0,-5);if(await exists(join(root,"src/app/eval-hub/evals/recipes",name+".json"))){const l=await readEvalLayers(root,"recipes",name);er.push("| "+tick+name+tick+" | "+tick+"evals/recipes/"+name+".json"+tick+" | "+(l.agents.map(x=>tick+x+tick).join(", ")||"—")+" | "+l.skills.map(x=>tick+x+tick).join(", ")+" |");}}
 const changes:Array<[string,string,string]>=[[join(root,"README.md"),"skills-table",sr.join("\n")],[join(root,"README.md"),"agents-table",ar.join("\n")],[join(root,"docs/internal/15-skill-evaluations.md"),"eval-skills",es.join("\n")],[join(root,"docs/internal/15-skill-evaluations.md"),"eval-agents",ea.join("\n")],[join(root,"docs/internal/15-skill-evaluations.md"),"eval-recipes",er.join("\n")]];let changed=0,stdout="";
 for(const [path,section,content] of changes){if(!await exists(path)){stdout+="  [skipped  ] "+path.split("/").at(-1)+":"+section+" (file moved or restructured)\n";continue;}const current=await readFile(path,"utf8"),result=injectGenerated(current,section,content);if(!result.found)stdout+="  [WARN] No marker found in "+path+" for section: "+section+"\n";if(result.changed){await writeFile(path,result.text);changed++;}stdout+="  ["+(result.changed?"updated":"unchanged").padEnd(9)+"] "+path.split("/").at(-1)+":"+section+"\n";}
 stdout+="\n  "+changed+"/"+changes.length+" section(s) updated.\n";return{changed,total:changes.length,stdout};}
async function main(){const root=resolve(dirname(fileURLToPath(import.meta.url)),"../../../..");process.stdout.write((await generateTables(root)).stdout);}if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))void main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1;});
