import { createHash, randomUUID } from "node:crypto";
import { closeSync, fstatSync, lstatSync, openSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { hostname } from "node:os";
import { chmod, lstat, mkdir, readFile, readdir, realpath, rename, rm, stat, symlink, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, relative, resolve, sep } from "node:path";
import { spawn } from "node:child_process";

export async function sha256File(path:string){return createHash("sha256").update(await readFile(path)).digest("hex")}
export function stable(value:unknown):unknown{if(Array.isArray(value))return value.map(stable);if(value!==null&&typeof value==="object")return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([k,v])=>[k,stable(v)]));return value}
export function compactJson(value:unknown){return JSON.stringify(stable(value))+"\n"}
export function prettyJson(value:unknown){return JSON.stringify(stable(value),null,2)+"\n"}
export async function exists(path:string){try{await lstat(path);return true}catch{return false}}
export async function run(command:string,args:string[],options:{cwd?:string,stdout?:"inherit"|"pipe"}={}):Promise<string>{return await new Promise((ok,fail)=>{const child=spawn(command,args,{cwd:options.cwd,stdio:["ignore",options.stdout??"pipe","pipe"]});let out="",err="";child.stdout?.on("data",x=>out+=String(x));child.stderr?.on("data",x=>err+=String(x));child.on("error",fail);child.on("close",code=>code===0?ok(out):fail(new Error((err||out||command+" failed").trim())))})}
export function parseArgs(argv:string[],positionals:string[]=[]){const values:Record<string,string|boolean>={},pos:string[]=[];for(let i=0;i<argv.length;i++){const arg=argv[i]!;if(!arg.startsWith("--")){pos.push(arg);continue}const key=arg.slice(2);const next=argv[i+1];if(next!==undefined&&!next.startsWith("--")){values[key]=next;i++}else values[key]=true}for(let i=0;i<positionals.length;i++)if(pos[i]!==undefined)values[positionals[i]!]=pos[i]!;if(pos.length>positionals.length)throw new Error("unexpected argument: "+pos[positionals.length]);return values}
export function required(args:Record<string,string|boolean>,name:string){const v=args[name];if(typeof v!=="string"||v==="")throw new Error("missing --"+name);return v}
export async function archiveEntries(archive:string){const text=await run("tar",["-tf",archive]);return text.split("\n").filter(Boolean)}
export function validateArchivePaths(entries:string[]){for(const name of entries){const normalized=name.replace(/\\/g,"/");if(isAbsolute(normalized)||normalized.split("/").some(x=>x===".."))throw new Error("archive path escape")}}
export async function extractArchive(archive:string,destination:string){const entries=await archiveEntries(archive);validateArchivePaths(entries);const verbose=await run("tar",["-tvf",archive]);for(const line of verbose.split("\n"))if(line!==""&&(line[0]==="l"||line[0]==="h"))throw new Error("archive link entry rejected");await run("tar",["-xf",archive,"-C",destination,"--no-same-owner","--no-same-permissions"])}
export async function atomicSymlink(current:string,target:string){const temp=resolve(dirname(current),".current.tmp");await rm(temp,{force:true});await symlink(target,temp);await rename(temp,current)}
type LockOwner={pid:number,hostname:string,token:string};
function parseLockOwner(text:string):LockOwner|null{try{const value=JSON.parse(text) as Partial<LockOwner>;return Number.isSafeInteger(value.pid)&&value.pid!>0&&typeof value.hostname==="string"&&value.hostname!==""&&typeof value.token==="string"&&value.token!==""?value as LockOwner:null}catch{return null}}
function processIsLive(pid:number){try{process.kill(pid,0);return true}catch(e){return (e as NodeJS.ErrnoException).code==="EPERM"}}
function sameFile(a:{dev:number|bigint,ino:number|bigint},b:{dev:number|bigint,ino:number|bigint}){return a.dev===b.dev&&a.ino===b.ino}
function sameOwner(a:LockOwner,b:LockOwner){return a.pid===b.pid&&a.hostname===b.hostname&&a.token===b.token}
export async function acquireLock(path:string){const owner:LockOwner={pid:process.pid,hostname:hostname(),token:randomUUID()};for(let attempt=0;attempt<8;attempt++){let fd:number;try{fd=openSync(path,"wx",0o600);writeFileSync(fd,JSON.stringify(owner)+"\n");let released=false;const identity=fstatSync(fd);return ()=>{if(released)return;released=true;closeSync(fd);let currentFd:number|undefined;try{currentFd=openSync(path,"r");const current=parseLockOwner(readFileSync(currentFd,"utf8"));if(sameFile(identity,fstatSync(currentFd))&&sameFile(identity,lstatSync(path))&&current!==null&&sameOwner(owner,current))unlinkSync(path)}catch{}finally{if(currentFd!==undefined)closeSync(currentFd)}}}catch(e){if((e as NodeJS.ErrnoException).code!=="EEXIST")throw new Error("installer locked",{cause:e})}let staleFd:number;try{staleFd=openSync(path,"r")}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")continue;throw new Error("installer locked",{cause:e})}let identity:ReturnType<typeof fstatSync>,current:LockOwner|null;try{identity=fstatSync(staleFd);current=parseLockOwner(readFileSync(staleFd,"utf8"))}finally{closeSync(staleFd)}if(current===null)throw new Error("installer locked: malformed owner metadata");if(current.hostname!==hostname()||processIsLive(current.pid))throw new Error("installer locked");try{if(!sameFile(identity,lstatSync(path)))continue;unlinkSync(path)}catch(e){if((e as NodeJS.ErrnoException).code!=="ENOENT")throw new Error("installer locked",{cause:e})}}throw new Error("installer locked: contention retry exhausted")}
export async function withLock<T>(path:string,operation:()=>Promise<T>){const release=await acquireLock(path);try{return await operation()}finally{release()}}
export function isMain(url:string){return process.argv[1]!==undefined&&resolve(process.argv[1])===resolve(new URL(url).pathname)}
export async function switchExecutable(path:string){await chmod(path,(await stat(path)).mode|0o111)}
export async function safeResolvedChild(base:string,child:string){const target=resolve(base,child);const rel=relative(resolve(base),target);if(rel===".."||rel.startsWith(".."+sep))throw new Error("path escape");return target}
