import { copyFile, mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { parseDocument } from "yaml";
export interface SlashCommand { command: string; recipe_path: string }
export async function packageHasBuildScript(packageJson: string): Promise<boolean> { try { const value: unknown = JSON.parse(await readFile(packageJson, "utf8")); if (!value || typeof value !== "object") return false; const scripts = (value as { scripts?: unknown }).scripts; return !!scripts && typeof scripts === "object" && typeof (scripts as Record<string, unknown>).build === "string"; } catch { return false; } }
export function upsertSlashCommands(source: string, managed: SlashCommand[]): string { const document = parseDocument(source || "{}", { keepSourceTokens: true }); if (document.errors.length) throw new Error(document.errors[0]?.message ?? "invalid YAML"); const root = document.toJS() as { slash_commands?: unknown }; const entries = Array.isArray(root.slash_commands) ? root.slash_commands : []; const names = new Set(managed.map(item => item.command.toLowerCase())); const kept = entries.filter(item => { if (!item || typeof item !== "object") return false; const command = (item as { command?: unknown }).command; return typeof command === "string" && !names.has(command.toLowerCase()); }); document.set("slash_commands", [...kept, ...managed]); return document.toString({ lineWidth: 0 }); }
async function isFile(path: string): Promise<boolean> { try { return (await stat(path)).isFile(); } catch { return false; } }
async function updateSlashCommands(args: string[]): Promise<number> { const [config, scanDir, recipeDir, backup, dryRun, stamp] = args; if (!config || !scanDir || !recipeDir || !backup || !dryRun || !stamp) throw new Error("usage: update-slash-commands <config> <scan-dir> <recipe-dir> <backup:0|1> <dry-run:0|1> <stamp>"); const files = (await readdir(scanDir)).filter(file => file.endsWith(".yaml")).sort(); const managed = files.map(file => ({ command: file.slice(0, -5), recipe_path: join(recipeDir, file) })); if ((await Promise.all(files.map(file => isFile(join(scanDir, file))))).some(present => !present)) { console.error("warning: cannot add slash commands; missing source recipes"); return 0; } if (dryRun === "1") { console.log("[dry-run] upsert slash_commands:"); for (const item of managed) console.log("  /" + item.command + " -> " + item.recipe_path); return 0; } let source = ""; if (await isFile(config)) source = await readFile(config, "utf8"); await mkdir(dirname(config), { recursive: true }); if (source && backup === "1") await copyFile(config, join(dirname(config), "config.yaml.backup-" + stamp)); await writeFile(config, upsertSlashCommands(source, managed)); console.log("Updated slash_commands in", config); for (const item of managed) console.log("  /" + item.command + " -> " + item.recipe_path); return 0; }
export async function runInstallSupport(argv = process.argv.slice(2)): Promise<number> { const [command, ...args] = argv; if (command === "has-build-script") return await packageHasBuildScript(args[0] ?? "") ? 0 : 1; if (command === "update-slash-commands") return updateSlashCommands(args); throw new Error("usage: install-support <has-build-script|update-slash-commands> ..."); }
if (import.meta.url === "file://" + process.argv[1]) runInstallSupport().then(code => { process.exitCode = code; }).catch(error => { console.error(error instanceof Error ? error.message : error); process.exitCode = 2; });
