#!/usr/bin/env node
import {createHash} from "node:crypto";
import {readFile} from "node:fs/promises";
import {resolve} from "node:path";

export interface EvidenceSummary {source:string;sha256:string;issue_count:number;invalid_json_lines:{line:number;error:string}[];by_status:Record<string,number>;by_type:Record<string,number>;by_priority:Record<string,number>;ready_count:number;blocked_or_dependent_count:number;dependency_link_counts:Record<string,number>;dependency_type_counts:Record<string,number>;epic_or_parent_link_count:number;sample_ready_ids:unknown[];sample_blocked_or_dependent_ids:unknown[]}
type Issue=Record<string,unknown>;
const count=(values:string[])=>Object.fromEntries([...new Set(values)].sort().map(k=>[k,values.filter(v=>v===k).length]));
const list=(v:unknown):unknown[]=>Array.isArray(v)?v:[];
export function buildBeadsEvidence(raw:Buffer,source:string):EvidenceSummary{
 const issues:Issue[]=[],invalid:{line:number;error:string}[]=[];
 raw.toString("utf8").split(/\r?\n/).forEach((line,index)=>{if(!line.trim())return;try{issues.push(JSON.parse(line) as Issue)}catch(e){invalid.push({line:index+1,error:e instanceof Error?e.message:String(e)})}});
 const links:Record<string,number>={},depTypes:string[]=[],dependentIds=new Set<unknown>();let parents=0;
 for(const issue of issues){const dependencies=list(issue.dependencies);if(Array.isArray(issue.dependencies)){links.dependencies=(links.dependencies??0)+dependencies.length;for(const d of dependencies)if(d&&typeof d==="object"){const dep=d as Issue;depTypes.push(String(dep.type??"unknown"));if(dep.depends_on_id)dependentIds.add(issue.id)}}for(const key of["depends_on","blocked_by","children"]){const v=issue[key];if(Array.isArray(v))links[key]=(links[key]??0)+v.length;else if(v)links[key]=(links[key]??0)+1}if(issue.parent||issue.epic_id||dependencies.some(d=>d&&typeof d==="object"&&(d as Issue).type==="parent-child"))parents++}
 const blocked=issues.filter(x=>["blocked","blocker"].includes(String(x.status??"").toLowerCase())||Boolean(x.blocked_by)||Boolean(x.depends_on)||dependentIds.has(x.id)||Number(x.dependency_count??0)>0);
 const ready=issues.filter(x=>["open","ready","todo"].includes(String(x.status??"").toLowerCase())&&!blocked.includes(x));
 return{source,sha256:createHash("sha256").update(raw).digest("hex"),issue_count:issues.length,invalid_json_lines:invalid,by_status:count(issues.map(x=>String(x.status??"unknown"))),by_type:count(issues.map(x=>String(x.issue_type??x.type??"unknown"))),by_priority:count(issues.map(x=>String(x.priority??"unknown"))),ready_count:ready.length,blocked_or_dependent_count:blocked.length,dependency_link_counts:Object.fromEntries(Object.entries(links).sort()),dependency_type_counts:count(depTypes),epic_or_parent_link_count:parents,sample_ready_ids:ready.slice(0,10).map(x=>x.id),sample_blocked_or_dependent_ids:blocked.slice(0,10).map(x=>x.id)};
}
function sortedJson(value:unknown):unknown{if(Array.isArray(value))return value.map(sortedJson);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,sortedJson(v)]));return value}
export function formatBeadsEvidence(s:EvidenceSummary,format:"json"|"md"):string{if(format==="json")return JSON.stringify(sortedJson(s),null,2)+"\n";const out=["# Beads Read-only Evidence",`- Source: ${s.source}`,`- SHA256: ${s.sha256}`,`- Issues: ${s.issue_count}`,`- Invalid JSON lines: ${s.invalid_json_lines.length}`,`- Ready: ${s.ready_count}`,`- Blocked/dependent: ${s.blocked_or_dependent_count}`,`- Epic/parent links: ${s.epic_or_parent_link_count}`];for(const[title,key]of[["Status counts","by_status"],["Type counts","by_type"],["Priority counts","by_priority"],["Dependency fields","dependency_link_counts"],["Dependency types","dependency_type_counts"]]as const){out.push("",`## ${title}`);for(const[k,v]of Object.entries(s[key]))out.push(`- ${k}: ${v}`)}out.push("","## Samples","- Ready IDs: "+s.sample_ready_ids.map(String).join(", "),"- Blocked/dependent IDs: "+s.sample_blocked_or_dependent_ids.map(String).join(", "));return out.join("\n")+"\n"}
const help="Usage: beads-readonly-evidence [--issues PATH] [--format json|md]";function usage():never{console.error(help);process.exit(2)}
async function main(){const args=process.argv.slice(2);let source=".beads/issues.jsonl",format:"json"|"md"="md";for(let i=0;i<args.length;i++){const arg=args[i]??"";if(arg==="-h"||arg==="--help"){console.log(help);return}else if(arg==="--issues")source=args[++i]??usage();else if(arg.startsWith("--issues="))source=arg.slice(9);else if(arg==="--format"||arg.startsWith("--format=")){const value=arg==="--format"?args[++i]:arg.slice(9);if(value!=="json"&&value!=="md")usage();format=value}else usage()}process.stdout.write(formatBeadsEvidence(buildBeadsEvidence(await readFile(source),source),format))}
if(process.argv[1]&&import.meta.url===new URL("file:"+resolve(process.argv[1])).href)void main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1});
