import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { describe, expect, it } from "vitest";
function root(){let p=process.cwd();while(!existsSync(resolve(p,"src/skills/evidence-verification/SKILL.md"))){const n=dirname(p);if(n===p)throw new Error("repository root not found");p=n;}return p;}
const paths={skill:"src/skills/evidence-verification/SKILL.md",standard:"src/agents/independent-verifier.md",premium:"src/agents/independent-verifier-premium.md",corpus:"src/app/eval-hub/evals/agents/independent-verifier.json"};
const read=(key:keyof typeof paths)=>readFileSync(resolve(root(),paths[key]),"utf8");
describe("independent verifier semantic contract",()=>{
 it("requires complete semantic lifecycle evidence",()=>{const skill=read("skill").toLowerCase(),standard=read("standard").toLowerCase(),premium=read("premium").toLowerCase();for(const marker of ["external id","shared config","serialization","provider","precedence","mutable routing","factory","session","ui","cache","invariant ledger","lifecycle map","producer-consumer","production constructor fidelity","serialization boundary","mutation + precedence matrix","fresh-patch second pass"])expect(skill+standard+premium).toContain(marker);for(const artifact of [skill,standard])for(const marker of ["clone","copy","inherit"])expect(artifact).toContain(marker);expect(standard).toContain("semantic_review");expect(standard).toMatch(/unclassified significant consumer[\s\S]{0,140}(block|must block) accepted/i);expect(premium).toMatch(/independently reconstruct/i);expect(premium).toMatch(/new probe dimension/i);});
 it("binds each adversarial scenario to one exact verdict",()=>{const corpus=JSON.parse(read("corpus")) as Array<{skills:string[];query:string;expected_behavior:string[]}>;expect(corpus.length).toBeGreaterThanOrEqual(8);for(const s of corpus)expect(s.skills).toEqual(["evidence-verification","loop-control"]);const obligations:[string,string][]=[["simplified constructor","production-constructor path"],["generic map payload","internal fields leak"],["mutable identifier","stable identifier invariant"],["early return","stale precedence"],["ui/session versus wire","wire identities diverge"]];for(const [queryMarker,reason] of obligations){const scenario=corpus.find(s=>s.query.toLowerCase().includes(queryMarker));expect(scenario,queryMarker).toBeDefined();const exact=scenario!.expected_behavior.filter(x=>x.startsWith("Returns exactly one verdict:"));expect(exact).toHaveLength(1);expect(exact[0]).toContain("REWORK");expect(exact[0]!.toLowerCase()).toContain(reason);}});
});
