export type DistributionComponent={id:string;kind:"skill"|"agent"|"recipe"|"plugin";name:string;ownership:"internal"|"external";distributionType:"native-skill-package"|"native-goose-plugin"|"embedded-release"|"recipe-copy"|"agent-copy";candidate:{mode:"locked-resolver"|"release-copy";authoritative:true;command?:string[]};source?:{repository:string;revision:string;path:string};nativeDistributionGate?:{optional:true;networkRequired:true;command:string[]};exemption?:{owner:string;reason:string;expiresAt:string}};
export type DistributionStrategy={schema:string;networkOptional:boolean;candidateBytesAuthoritative:boolean;resolver:{package:string;version:string};components:DistributionComponent[]};
type Inventory={components:Array<{kind:string;name:string;ownership:string}>};type Lock={skills:Array<{name:string;active:boolean;source:{repository:string;revision:string;path:string}}>};
const key=(x:{kind:string;name:string})=>`${x.kind}:${x.name}`;
const same=(a:string[],b:string[])=>a.length===b.length&&a.every((x,i)=>x===b[i]);
export function validateDistributionStrategy(strategy:DistributionStrategy,source:Inventory,runtime:Inventory,lock:Lock,now=new Date()):string[]{const errors:string[]=[];const activeKinds=new Set(["skill","agent","recipe","plugin"]);const expected=[...new Set(source.components.filter(x=>activeKinds.has(x.kind)).map(key))].sort();const runtimeExpected=[...new Set(runtime.components.filter(x=>activeKinds.has(x.kind)).map(key))].sort();const actual=strategy.components.map(key).sort();
 if(!same(expected,runtimeExpected))errors.push("source/runtime component inventory mismatch");if(!same(expected,actual))errors.push("distribution coverage must exactly match active inventory");if(new Set(actual).size!==actual.length)errors.push("duplicate distribution component");if(!strategy.networkOptional||!strategy.candidateBytesAuthoritative)errors.push("candidate/network policy invalid");
 const locked=new Map(lock.skills.filter(x=>x.active).map(x=>[x.name,x]));for(const c of strategy.components){if(c.id!==key(c))errors.push(`id mismatch: ${c.id}`);const needsNative=c.distributionType==="native-skill-package"||c.distributionType==="native-goose-plugin";if(needsNative&&(!c.source||!c.nativeDistributionGate))errors.push(`native source/gate missing: ${c.id}`);if(c.source&&!/^[0-9a-f]{40}$/.test(c.source.revision))errors.push(`immutable revision required: ${c.id}`);
  if(c.ownership==="external"&&c.kind==="skill"){const l=locked.get(c.name);if(!l)errors.push(`active external lock missing: ${c.id}`);else if(!c.source||c.source.repository!==`https://github.com/${l.source.repository}`||c.source.revision!==l.source.revision||c.source.path!==l.source.path)errors.push(`external source differs from lock: ${c.id}`)}
  for(const command of [c.candidate.command,c.nativeDistributionGate?.command].filter(Boolean) as string[][]){const joined=command.join(" ");if(joined.includes("npx")&&!joined.includes("skills@1.5.20"))errors.push(`unpinned skills command: ${c.id}`);if(joined.includes("goose plugin")&&c.distributionType!=="native-goose-plugin")errors.push(`ineligible goose plugin command: ${c.id}`)}
  if(c.distributionType==="embedded-release"){if(!c.exemption)errors.push(`embedded exemption missing: ${c.id}`);else if(!Number.isFinite(Date.parse(c.exemption.expiresAt))||Date.parse(c.exemption.expiresAt)<=now.getTime())errors.push(`embedded exemption expired: ${c.id}`)}
 }
 for(const name of locked.keys())if(!strategy.components.some(c=>c.kind==="skill"&&c.name===name&&c.ownership==="external"))errors.push(`locked active skill omitted: ${name}`);return errors;}
